#!/usr/bin/env python3
"""Generates the user guide chapters that mirror stepss-docs.

The printed guide and the website document the same platform, and for a long
while the guide covered a subset: it had the data formats and the CODEGEN
block library, and nothing at all on the two user interfaces, the model
library, small-signal analysis, the Python API or the test systems. Writing
those by hand would have produced a second copy that drifts, so they are
generated from the site's own Markdown instead.

Hand-written chapters are never touched. `MANIFEST` lists only the pages that
have no counterpart in the guide, and every file it writes carries a header
saying it is generated and must not be edited by hand.

    ./tools/from_docs.py            # regenerate everything in MANIFEST
    ./tools/from_docs.py --check    # fail if any output is stale

The conversion is pandoc, with a preprocessor that turns Starlight's MDX
components and directives into things pandoc understands, and a postprocessor
that fixes what its LaTeX writer gets wrong for this document.
"""

from __future__ import annotations

import argparse
import math
import pathlib
import re
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
GUIDE = HERE.parent
DOCS = GUIDE.parent / "stepss-docs"
SRC = DOCS / "src" / "content" / "docs"
PUBLIC = DOCS / "public"
GEN = GUIDE / "generated"
FIG = GUIDE / "figures"

BANNER = (
    "%% GENERATED by tools/from_docs.py from stepss-docs. Do not edit by hand:\n"
    "%% edit the page named below in stepss-docs and regenerate.\n"
    "%% source: {source}\n"
)

# page slug -> (output stem, chapter title). Order is the order they appear in
# the guide; stepss_doc.tex includes them by stem.
MANIFEST: list[tuple[str, str, str]] = [
    # Part: getting started
    ("getting-started/quickstart", "quickstart", "Driving the engines: GUI and Python"),
    # Part: STEPSS GUI
    ("gui/first-run", "gui-first-run", "First run of STEPSS GUI"),
    ("gui/interface", "gui-interface", "The STEPSS GUI interface"),
    ("gui/running", "gui-running", "Running a simulation in STEPSS GUI"),
    # Part: dynamic simulation
    ("user-guide/eigenanalysis", "eigenanalysis", "Small-signal stability analysis"),
    ("models/discrete-controllers", "model-dctl", "Discrete controller models"),
    # Part: model library
    ("models/index", "model-index", "The model library"),
    ("models/synchronous-machine", "model-sync", "Synchronous machine models"),
    (
        "models/synchronous-machine-param-conversion",
        "model-sync-conv",
        "Synchronous machine parameter conversion",
    ),
    ("models/ieee-exciters", "model-exc-ieee", "IEEE excitation controllers"),
    ("models/custom-exciters", "model-exc-custom", "Other excitation controllers"),
    ("models/ieee-governors", "model-tor-ieee", "IEEE turbine-governor models"),
    ("models/custom-governors", "model-tor-custom", "Other turbine-governor models"),
    ("models/custom-injectors", "model-inj", "Injector models"),
    ("models/two-port-models", "model-twop", "Two-port models"),
    # Part: CODEGEN
    ("developer/codegen-examples", "codegen-examples", "Worked CODEGEN examples"),
    ("developer/cg-studio", "cg-studio", "CODEGEN Studio"),
    # Part: Python
    ("python/overview", "py-overview", "STEPSS in Python"),
    ("python/installation", "py-install", "Installing the Python package"),
    ("python/examples", "py-examples", "Python examples"),
    ("python/api-reference", "py-api", "Python API reference"),
    ("python/helios", "py-helios", "Power flow from Python"),
    ("developer/uramses", "uramses", "uRAMSES, the C and Fortran interface"),
    # Part: reference
    ("test-systems/index", "ts-index", "Test systems"),
    ("test-systems/5bus", "ts-5bus", "The 5-bus tutorial system"),
    ("test-systems/kundur", "ts-kundur", "The Kundur two-area system"),
    ("test-systems/nordic", "ts-nordic", "The IEEE Nordic test system"),
    ("test-systems/gb-network", "ts-gb", "The Great Britain network"),
    ("resources/repositories", "res-repos", "Component repositories"),
    ("resources/references", "res-refs", "References"),
]

# Every slug the guide can link to, generated or hand-written.
LABELS: dict[str, str] = {slug: f"doc:{stem}" for slug, stem, _ in MANIFEST}
LABELS.update(
    {
        "getting-started/overview": "ch-overview",
        "getting-started/installation": "ch-install",
        "getting-started/license": "ch-legal",
        "user-guide/file-formats": "ch-files",
        "user-guide/network": "ch-network",
        "user-guide/power-flow": "ch-pf",
        "user-guide/reference-frames": "ch-refinit",
        "user-guide/dynamic-models": "ch-sync",
        "user-guide/disturbances": "ch-disturb",
        "user-guide/solver-settings": "ch-settings",
        "developer/user-models": "ch-user_models",
        "developer/codegen-blocks": "ch-libray_blocks",
    }
)
# Section index pages are linked both with and without the /index suffix.
LABELS.update(
    {
        "models": LABELS["models/index"],
        "test-systems": LABELS["test-systems/index"],
        "python": LABELS["python/overview"],
        "gui": LABELS["gui/interface"],
        "developer/codegen-blocks/algebraic": "ch-libray_blocks",
        "developer/codegen-blocks/automata": "ch-libray_blocks",
        "developer/codegen-blocks/controllers": "ch-libray_blocks",
        "developer/codegen-blocks/frequency": "ch-libray_blocks",
        "developer/codegen-blocks/functions": "ch-libray_blocks",
        "developer/codegen-blocks/integrators": "ch-libray_blocks",
        "developer/codegen-blocks/limiters": "ch-libray_blocks",
        "developer/codegen-blocks/transfer-functions": "ch-libray_blocks",
    }
)

NOTE_KINDS = {"note": "Note", "tip": "Tip", "caution": "Caution", "danger": "Warning"}

# The guide is built with pdflatex under OT1 fonts, and every hand-written
# source in it is pure ASCII. The site is not: its fenced blocks draw block
# diagrams out of box-drawing characters and label them with Greek. Rather
# than move a 186-page document to a Unicode engine for the sake of the
# generated chapters, both are mapped here. Inside a code fence the target has
# to be ASCII, because verbatim takes no commands; outside one it can be the
# proper LaTeX.
CODE_MAP = {
    "\u2500": "-", "\u2502": "|", "\u250c": "+", "\u2510": "+", "\u2514": "+",
    "\u2518": "+", "\u251c": "+", "\u2524": "+", "\u252c": "+", "\u2534": "+",
    "\u253c": "+", "\u2550": "=", "\u2551": "|",
    "\u2192": "->", "\u2190": "<-", "\u2194": "<->", "\u21d2": "=>",
    "\u25ba": ">", "\u25c4": "<", "\u279c": "->", "\u2022": "*",
    "\u00b7": "*", "\u00d7": "x", "\u2212": "-", "\u2013": "-", "\u2014": "-",
    "\u2264": "<=", "\u2265": ">=", "\u00b1": "+/-", "\u222b": "integral",
    "\u2713": "yes", "\u2019": "'", "\u2018": "'", "\u201c": '"', "\u201d": '"',
    "\u0391": "Alpha", "\u0392": "Beta", "\u0393": "Gamma", "\u0394": "Delta",
    "\u03a9": "Ohm", "\u03a3": "Sigma", "\u03a6": "Phi", "\u03a8": "Psi",
    "\u03b1": "alpha", "\u03b2": "beta", "\u03b3": "gamma", "\u03b4": "delta",
    "\u03b5": "eps", "\u03b6": "zeta", "\u03b7": "eta", "\u03b8": "theta",
    "\u03bb": "lambda", "\u03bc": "mu", "\u03c0": "pi", "\u03c1": "rho",
    "\u03c3": "sigma", "\u03c4": "tau", "\u03c6": "phi", "\u03c8": "psi",
    "\u03c9": "omega",
    "\u00e9": "e", "\u00e8": "e", "\u00c9": "E", "\u00e0": "a", "\u00fc": "u",
}
TEXT_MAP = {
    "\u2013": "--", "\u2014": "---", "\u2212": "\\ensuremath{-}", "\u00d7": "\\ensuremath{\\times}",
    "\u00b7": "\\ensuremath{\\cdot}", "\u2192": "\\ensuremath{\\rightarrow}", "\u2190": "\\ensuremath{\\leftarrow}",
    "\u2194": "\\ensuremath{\\leftrightarrow}", "\u2264": "\\ensuremath{\\le}", "\u2265": "\\ensuremath{\\ge}",
    "\u00b1": "\\ensuremath{\\pm}", "\u222b": "\\ensuremath{\\int}", "\u2713": "yes",
    "\u2019": "'", "\u2018": "`", "\u201c": "``", "\u201d": "''",
    "\u00e9": "\\'e", "\u00e8": "\\`e", "\u00c9": "\\'E", "\u00e0": "\\`a",
    "\u00fc": '\\"u',
    "\u0394": "\\ensuremath{\\Delta}", "\u03a9": "\\ensuremath{\\Omega}", "\u03b1": "\\ensuremath{\\alpha}",
    "\u03b2": "\\ensuremath{\\beta}", "\u03b3": "\\ensuremath{\\gamma}", "\u03b6": "\\ensuremath{\\zeta}",
    "\u03bb": "\\ensuremath{\\lambda}", "\u03c9": "\\ensuremath{\\omega}", "\u03c3": "\\ensuremath{\\sigma}",
    "\u03c4": "\\ensuremath{\\tau}", "\u03c6": "\\ensuremath{\\phi}", "\u03bc": "\\ensuremath{\\mu}",
    "\u279c": "\\ensuremath{\\rightarrow}", "\u25ba": "\\ensuremath{\\blacktriangleright}",
    "\u25c4": "\\ensuremath{\\blacktriangleleft}", "\u2022": "\\ensuremath{\\bullet}",
    "\u21d2": "\\ensuremath{\\Rightarrow}", "\u2500": "--", "\u2502": "|",
}
# Anything box-drawing that reaches prose is a diagram that lost its fence;
# fall back to the ASCII form rather than failing the run.
TEXT_MAP.update({k: v for k, v in CODE_MAP.items() if k not in TEXT_MAP})


VERBATIM_RE = re.compile(r"(?si)(\\begin\{verbatim\}.*?\\end\{verbatim\})")


def demote_latex(tex: str) -> str:
    """The same mapping over the finished LaTeX, split on verbatim rather than
    on fences. Markdown is not the only source of these characters: an HTML
    entity such as &#10003; is still an entity when the preprocessor sees it
    and a check mark by the time pandoc is done."""
    out = []
    for i, part in enumerate(VERBATIM_RE.split(tex)):
        table = CODE_MAP if i % 2 else TEXT_MAP
        for ch, rep in table.items():
            if ch in part:
                part = part.replace(ch, rep)
        out.append(part)
    return "".join(out)


# --------------------------------------------------------------- preprocess
def strip_frontmatter(text: str) -> tuple[str, dict[str, str]]:
    if not text.startswith("---"):
        return text, {}
    end = text.index("\n---", 3)
    meta = {}
    for line in text[3:end].splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip().strip("'\"")
    return text[end + 4 :].lstrip("\n"), meta


FENCE_RE = re.compile(r"^(?P<indent> {0,3})(?P<ticks>`{3,}|~{3,})(?P<info>.*)$")
MARK = "\x00CODE{}\x00"


def mask_code(text: str) -> tuple[str, list[str]]:
    """Replaces every fenced block with an opaque marker.

    A single mask, rather than a split repeated for each transformation, is
    what makes a directive that wraps a code block work: `:::note` and its
    closing `:::` end up in the same string with the block reduced to one
    token between them.

    The fence rule is CommonMark's, which is what the site is parsed by: up to
    three spaces of indent, and a closing fence of at least as many marks. An
    earlier version of this matched only column-zero backticks; most fences on
    the pages are indented inside a list, so it paired an opening fence with
    some later block's closing one and every transformation downstream of that
    point silently stopped firing.
    """
    lines = text.split("\n")
    out: list[str] = []
    blocks: list[str] = []
    buf: list[str] | None = None
    fence: tuple[str, str] | None = None
    for line in lines:
        m = FENCE_RE.match(line)
        if buf is None:
            if m and m.group("info").strip().count("`") == 0:
                buf = [line]
                fence = (m.group("ticks")[0], m.group("ticks"))
            else:
                out.append(line)
        else:
            buf.append(line)
            if (
                m
                and not m.group("info").strip()
                and m.group("ticks")[0] == fence[0]
                and len(m.group("ticks")) >= len(fence[1])
            ):
                out.append(MARK.format(len(blocks)))
                blocks.append("\n".join(buf))
                buf, fence = None, None
    if buf is not None:              # an unterminated fence: keep it as code
        out.append(MARK.format(len(blocks)))
        blocks.append("\n".join(buf))
    return "\n".join(out), blocks


def unmask_code(text: str, blocks: list[str]) -> str:
    for i, block in enumerate(blocks):
        text = text.replace(MARK.format(i), block)
    return text


def split_fences(text: str):
    """Kept for demote_latex, which splits finished LaTeX rather than Markdown."""
    masked, blocks = mask_code(text)
    yield False, masked
    for block in blocks:
        yield True, block


def raw_latex(body: str) -> str:
    return "\n\n```{=latex}\n" + body + "\n```\n\n"


def convert_admonitions(text: str) -> str:
    """`:::note[Title]` ... `:::` becomes an mdframed the guide already styles."""

    def repl(m: re.Match) -> str:
        kind, title, body = m.group(1), m.group(2), m.group(3)
        heading = title or NOTE_KINDS.get(kind, "Note")
        return (
            raw_latex("\\begin{docsnote}{" + tex_escape(heading) + "}")
            + body.strip("\n")
            + raw_latex("\\end{docsnote}")
        )

    return re.sub(
        r"(?ms)^:::(note|tip|caution|danger)(?:\[(.*?)\])?\s*$(.*?)^:::\s*$",
        repl,
        text,
    )


def convert_asides(text: str) -> str:
    def repl(m: re.Match) -> str:
        attrs, body = m.group(1), m.group(2)
        kind = (re.search(r'type="(\w+)"', attrs) or [None, "note"])[1]
        title = (re.search(r'title="([^"]*)"', attrs) or [None, None])[1]
        heading = title or NOTE_KINDS.get(kind, "Note")
        return (
            raw_latex("\\begin{docsnote}{" + tex_escape(heading) + "}")
            + body.strip("\n")
            + raw_latex("\\end{docsnote}")
        )

    return re.sub(r"(?ms)<Aside([^>]*)>(.*?)</Aside>", repl, text)


def convert_components(text: str) -> str:
    r"""Starlight's layout components carry no meaning a printed page keeps.

    The horizontal whitespace classes are `[ \t]`, deliberately: `\s` matches
    a newline, so `\s*$` ate the blank line that separated a `<Steps>` list
    from the paragraph above it and pandoc then ran the first item into that
    paragraph.
    """
    text = re.sub(r"(?m)^[ \t]*</?(Tabs|Steps|CardGrid)>[ \t]*$", "", text)
    text = re.sub(
        r'(?m)^[ \t]*<TabItem\s+label="([^"]*)"[^>]*>[ \t]*$',
        lambda m: f"\n**{m.group(1)}**\n",
        text,
    )
    text = re.sub(
        r'(?m)^[ \t]*<Card\s+title="([^"]*)"[^>]*>[ \t]*$',
        lambda m: f"\n**{m.group(1)}**\n",
        text,
    )
    text = re.sub(r"(?m)^[ \t]*</(TabItem|Card)>[ \t]*$", "", text)
    return text


IMG_RE = re.compile(r"<img\s+([^>]*?)/>", re.S)


def img_attrs(tag: str) -> dict[str, str]:
    return dict(re.findall(r'(\w[\w:-]*)="([^"]*)"', tag))


def convert_images(text: str, used: set[str]) -> str:
    """Keeps the light half of each light/dark pair; the page has one theme."""
    tags = list(IMG_RE.finditer(text))
    drop: set[int] = set()
    out = text
    replacements: list[tuple[int, int, str]] = []
    for i, m in enumerate(tags):
        if i in drop:
            continue
        attrs = img_attrs(m.group(1))
        src, cls = attrs.get("src", ""), attrs.get("class", "")
        if "light:sl-hidden" in cls:  # the dark half of a pair
            replacements.append((m.start(), m.end(), ""))
            continue
        nxt = tags[i + 1] if i + 1 < len(tags) else None
        if nxt and "light:sl-hidden" in img_attrs(nxt.group(1)).get("class", ""):
            drop.add(i + 1)
            replacements.append((nxt.start(), nxt.end(), ""))
        name = pathlib.Path(src).name
        used.add(src)
        caption = first_sentence(attrs.get("alt", ""))
        width = figure_width(attrs.get("style", ""), name)
        body = (
            "\\begin{figure}[htbp]\n\\centering\n"
            f"\\includegraphics[width={width}\\linewidth]{{figures/{pathlib.Path(name).stem}}}\n"
            + (f"\\caption{{{tex_escape(caption)}}}\n" if caption else "")
            + "\\end{figure}"
        )
        replacements.append((m.start(), m.end(), raw_latex(body)))

    for start, end, rep in sorted(replacements, reverse=True):
        out = out[:start] + rep + out[end:]
    return out


def figure_width(style: str, name: str) -> str:
    m = re.search(r"width:\s*(\d+)%", style)
    if m:
        return f"{int(m.group(1)) / 100:.2f}"
    if name.startswith(("py-", "gui-status-bar")):
        return "0.85"
    return "0.98"


def first_sentence(alt: str) -> str:
    alt = alt.strip()
    if not alt:
        return ""
    m = re.match(r"(.+?\.)(\s|$)", alt)
    return (m.group(1) if m else alt).strip()


LINK_RE = re.compile(r"\[([^\]]+)\]\((/[^)]*)\)")


def convert_links(text: str, unresolved: set[str]) -> str:
    """Site-internal links become cross-references, or plain text if the page
    has no counterpart here."""

    def repl(m: re.Match) -> str:
        label_text, href = m.group(1), m.group(2)
        slug = href.split("#")[0].strip("/")
        target = LABELS.get(slug)
        if target:
            return f"[{label_text}](#{target})"
        unresolved.add(slug)
        return label_text

    return LINK_RE.sub(repl, text)


def tex_escape(s: str) -> str:
    for a, b in (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ):
        s = s.replace(a, b)
    return s


def preprocess(text: str, used: set[str], unresolved: set[str]) -> str:
    text, _ = strip_frontmatter(text)
    text = re.sub(r"(?m)^import\s+.*?;\s*$\n?", "", text)
    prose, blocks = mask_code(text)
    prose = convert_asides(prose)
    prose = convert_admonitions(prose)
    prose = convert_components(prose)
    prose = convert_images(prose, used)
    prose = convert_links(prose, unresolved)
    # MDX escapes a literal brace as {'{'}; the printed page wants the brace.
    prose = prose.replace("{'{'}", "{").replace("{'}'}", "}")
    # Prose is left alone here. Mapping a Greek letter to math this early puts
    # a dollar next to one pandoc has not resolved yet, and the pair it then
    # picks is the wrong one; demote_latex does it after pandoc instead.
    blocks = [demote_block(b) for b in blocks]
    return unmask_code(prose, blocks)


def demote_block(block: str) -> str:
    for ch, rep in CODE_MAP.items():
        if ch in block:
            block = block.replace(ch, rep)
    return block


# -------------------------------------------------------------- postprocess
# ------------------------------------------------------------- table widths
LT_RE = re.compile(r"(?s)(\\begin\{longtable\}\[\]\{@\{\}\n)(.*?)(@\{\}\})(.*?)(\\end\{longtable\})")
COLSPEC_RE = re.compile(r">\{\\(raggedright|raggedleft|centering)\\arraybackslash\}p\{[^}]*\\real\{([0-9.]+)\}\}")
SKIP_ROW = ("\\toprule", "\\midrule", "\\bottomrule", "\\endhead",
            "\\endlastfoot", "\\endfirsthead", "\\noalign")


def strip_markup(cell: str) -> str:
    """Leaves roughly the ink a cell puts on the page.

    The link target is not ink: \\hyperref[doc:ts-kundur]{Kundur two-area} sets
    fifteen characters, not thirty-nine, and counting the label made every
    column of cross-references come out too wide.
    """
    t = re.sub(r"\\begin\{minipage\}[^\n]*|\\end\{minipage\}", " ", cell)
    t = re.sub(r"\\(raggedright|raggedleft|centering|arraybackslash|tightlist)\b", " ", t)
    t = re.sub(r"\\href\{[^}]*\}", "", t)
    t = re.sub(r"\\hyperref\[[^\]]*\]", "", t)
    t = re.sub(r"\\[a-zA-Z@]+\s*", "", t)
    return t


def visible_len(cell: str) -> int:
    """Roughly what the cell will occupy: LaTeX markup is not ink."""
    t = strip_markup(cell)
    t = re.sub(r"[{}$\\]", "", t)
    return len(" ".join(t.split()))


def longest_token(cell: str) -> int:
    t = strip_markup(cell)
    t = re.sub(r"[{}$\\]", "", t)
    return max((len(w) for w in t.split()), default=1)


TT_RE = re.compile(r"\\(?:texttt|Verb|lstinline)\{([^{}]*)\}")


def longest_tt_token(cell: str) -> int:
    """The longest run of typewriter text with nothing to break at.

    Prose hyphenates and a column narrower than its longest word is merely
    tight. An identifier such as stepss.helios.HeliosSession does not break:
    TeX will not hyphenate across the dots, so a column narrower than that
    token overflows into the next one however the rest of the table is
    proportioned. That is a floor, not a preference.
    """
    longest = 0
    for m in TT_RE.finditer(cell):
        text = re.sub(r"\\[a-zA-Z@]+\s*|[{}$]", "", m.group(1))
        text = text.replace("\\", "")
        for word in text.split():
            longest = max(longest, len(word))
    return longest


# Typewriter metrics of the built document: \small in an 11pt newpx body over
# a 448pt text block, which is a little under 90 characters, plus the cell's
# own 2\tabcolsep of padding.
TT_CHAR_PT = 5.0
CELL_PAD_PT = 14.0
TEXT_WIDTH_PT = 448.0
MAX_FLOOR = 0.45


def split_cells(row: str) -> list[str]:
    return re.split(r"(?<!\\)&", row)


def retable(tex: str) -> str:
    """Rewrites pandoc's column widths from the cells rather than the source.

    Pandoc takes each \real{} from the width of the column in the pipe table it
    parsed, which is how wide the author drew it in Markdown and has nothing to
    do with what is in it. A "What it is for" column holding sixty words and a
    "Buses" column holding one number come out the same size, and the prose is
    then squeezed into a ribbon down the page.

    Widths here are proportional to the square root of the mean cell length,
    which separates a prose column from a number column without letting one
    long cell take the whole table, with a floor from the longest unbreakable
    token so a column can always fit its widest identifier.
    """

    def fix(m: re.Match) -> str:
        head, spec, close, body, end = m.groups()
        cols = COLSPEC_RE.findall(spec)
        n = len(cols)
        if n < 2:
            return m.group(0)

        lengths = [[] for _ in range(n)]
        tokens = [1] * n
        tt = [0] * n
        for raw in body.split("\\\\"):
            if any(k in raw for k in SKIP_ROW) and "&" not in raw:
                continue
            cells = split_cells(raw)
            if len(cells) != n:
                continue
            for i, cell in enumerate(cells):
                lengths[i].append(visible_len(cell))
                tokens[i] = max(tokens[i], longest_token(cell))
                tt[i] = max(tt[i], longest_tt_token(cell))
        if not any(lengths):
            return m.group(0)

        raws = []
        for i in range(n):
            mean = sum(lengths[i]) / len(lengths[i]) if lengths[i] else 1.0
            raws.append(max(math.sqrt(max(mean, 1.0)), 0.55 * math.sqrt(tokens[i])))
        total = sum(raws)
        widths = [max(r / total, 0.05) for r in raws]

        # A column holding an unbreakable identifier gets at least the width
        # that identifier needs, taken out of the columns that can give it.
        floors = [
            min(MAX_FLOOR, (c * TT_CHAR_PT + CELL_PAD_PT) / TEXT_WIDTH_PT) if c else 0.0
            for c in tt
        ]
        if sum(floors) < 0.95:
            for _ in range(n):
                short = [i for i in range(n) if widths[i] < floors[i]]
                if not short:
                    break
                debt = sum(floors[i] - widths[i] for i in short)
                give = [i for i in range(n) if i not in short and widths[i] > 0.06]
                pool = sum(widths[i] for i in give)
                if not give or pool <= debt:
                    break
                for i in short:
                    widths[i] = floors[i]
                for i in give:
                    widths[i] -= debt * widths[i] / pool
        total = sum(widths)
        widths = [w / total for w in widths]

        new_spec = "".join(
            "  >{\\%s\\arraybackslash}p{(\\linewidth - %d\\tabcolsep) * \\real{%.4f}}\n"
            % (align, 2 * n, w)
            for (align, _), w in zip(cols, widths)
        )
        return head + new_spec + close + body + end

    return LT_RE.sub(fix, tex)


def postprocess(tex: str, stem: str) -> str:
    # pandoc labels every heading with a slug taken from its text, which is
    # what a same-page link on the site points at. Keep them, so those links
    # still resolve here, but namespace them: "overview" is a heading on a
    # dozen of these pages and LaTeX has one label space for the whole book.
    def ns(m: re.Match) -> str:
        head, name = m.group(1), m.group(2)
        close = "}" if head.endswith("{") else "]"
        if name.startswith(("doc:", "ch-", "sec:", "mdf@")):
            return m.group(0)
        return f"{head}{stem}:{name}{close}"

    tex = re.sub(r"(\\label\{)([^}]+)\}", lambda m: ns(m), tex)
    tex = re.sub(r"(\\hyperref\[)([^\]]+)\]", lambda m: ns(m), tex)
    # Its \texttt already escapes; \passthrough is only defined in its template.
    tex = tex.replace("\\passthrough", "")
    # A table wider than the text block is worse than a smaller one.
    tex = retable(tex)
    tex = tex.replace("\\begin{longtable}", "\\begin{small}\\begin{longtable}")
    tex = tex.replace("\\end{longtable}", "\\end{longtable}\\end{small}")
    # pandoc guards an uncaptioned longtable with {\def\LTcaptype{none} ... },
    # which suppresses the counter in a bare book class. sps-report.cls loads
    # the caption package, under which LTcaptype is a counter name and every
    # one of these raises "No counter 'none' defined". None of these tables has
    # a caption, so the guard has nothing to do here.
    tex = tex.replace("{\\def\\LTcaptype{none} % do not increment counter\n", "")
    tex = tex.replace("\\end{longtable}\\end{small}\n}\n", "\\end{longtable}\\end{small}\n")
    # fancyvrb's Verbatim, not the plain one, so fvextra can break a data
    # record that is wider than this text block instead of running it off the
    # page. Several records in the model chapters are.
    tex = tex.replace("\\begin{verbatim}", "\\begin{Verbatim}")
    tex = tex.replace("\\end{verbatim}", "\\end{Verbatim}")
    tex = demote_latex(tex)
    return tex.strip() + "\n"


def build_page(slug: str, stem: str, title: str, used: set[str], unresolved: set[str]) -> str:
    path = SRC / slug
    for ext in (".md", ".mdx"):
        if (path.with_suffix(ext)).exists():
            path = path.with_suffix(ext)
            break
        if (path / "index.md").exists():
            path = path / "index.md"
            break
    else:
        raise SystemExit(f"no source for {slug}")

    md = preprocess(path.read_text(), used, unresolved)
    out = subprocess.run(
        [
            "pandoc",
            "--from=markdown+raw_tex",
            "--to=latex",
            "--syntax-highlighting=none",
            "--top-level-division=section",
            "--shift-heading-level-by=-1",
            "--wrap=preserve",
        ],
        input=md,
        text=True,
        capture_output=True,
    )
    if out.returncode:
        raise SystemExit(f"pandoc failed on {slug}:\n{out.stderr}")

    body = postprocess(out.stdout, stem)
    header = BANNER.format(source=path.relative_to(DOCS.parent))
    return f"{header}\n\\chapter{{{title}}}\\label{{{LABELS[slug]}}}\n\n{body}"


# ------------------------------------------------------------------ figures
def collect_figures(used: set[str]) -> list[str]:
    FIG.mkdir(exist_ok=True)
    names = []
    for src in sorted(used):
        source = PUBLIC / src.lstrip("/")
        if not source.exists():
            print(f"  ! missing figure {src}", file=sys.stderr)
            continue
        stem = source.stem
        if source.suffix == ".svg":
            target = FIG / f"{stem}.pdf"
            subprocess.run(
                ["rsvg-convert", "-f", "pdf", "-o", str(target), str(source)], check=True
            )
        else:
            target = FIG / source.name
            shutil.copy2(source, target)
        names.append(target.name)
    return names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if anything is stale")
    args = ap.parse_args()

    if not SRC.is_dir():
        raise SystemExit(f"{SRC} not found: this needs the stepss-docs checkout beside the guide")

    GEN.mkdir(exist_ok=True)
    used: set[str] = set()
    unresolved: set[str] = set()
    stale = []
    for slug, stem, title in MANIFEST:
        text = build_page(slug, stem, title, used, unresolved)
        target = GEN / f"{stem}.tex"
        if args.check:
            if not target.exists() or target.read_text() != text:
                stale.append(target.name)
        else:
            stray = sorted({c for c in text if ord(c) > 127})
            if stray:
                raise SystemExit(
                    f"{stem}.tex still holds characters pdflatex cannot set: "
                    + " ".join(f"U+{ord(c):04X} {c!r}" for c in stray)
                    + "\nAdd them to CODE_MAP and TEXT_MAP."
                )
            target.write_text(text)
            print(f"  {target.relative_to(GUIDE)}")

    if not args.check:
        figures = collect_figures(used)
        print(f"  {len(figures)} figures into figures/")
        if unresolved:
            print("  links flattened to plain text (no chapter here):", file=sys.stderr)
            for slug in sorted(unresolved):
                print(f"    /{slug}/", file=sys.stderr)

    if stale:
        print("stale, re-run tools/from_docs.py: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
